// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function CancelAIChat(arg1:string):Promise<void>;

export function ConnectSSH(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function DisconnectSSH():Promise<string>;

export function GetAppState():Promise<config.AppState>;

export function GetConnectionLabel():Promise<string>;

export function SaveChatForModel(arg1:string,arg2:Array<config.ChatMsg>):Promise<void>;

export function SaveServers(arg1:Array<config.LinuxServer>):Promise<void>;

export function SendSSHInput(arg1:string):Promise<void>;

export function SetActiveAIModel(arg1:string):Promise<void>;

export function StartAIChat(arg1:Array<main.ChatMessage>):Promise<string>;

export function UpsertAIModel(arg1:string,arg2:string):Promise<config.AIModel>;

export function UpsertAIModelV2(arg1:string,arg2:string,arg3:string):Promise<config.AIModel>;

export function UpsertAIModelV3(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<config.AIModel>;
