// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAIChat(arg1) {
  return window['go']['main']['App']['CancelAIChat'](arg1);
}

export function ConnectSSH(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2, arg3, arg4);
}

export function DisconnectSSH() {
  return window['go']['main']['App']['DisconnectSSH']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetConnectionLabel() {
  return window['go']['main']['App']['GetConnectionLabel']();
}

export function SaveChatForModel(arg1, arg2) {
  return window['go']['main']['App']['SaveChatForModel'](arg1, arg2);
}

export function SaveServers(arg1) {
  return window['go']['main']['App']['SaveServers'](arg1);
}

export function SendSSHInput(arg1) {
  return window['go']['main']['App']['SendSSHInput'](arg1);
}

export function SetActiveAIModel(arg1) {
  return window['go']['main']['App']['SetActiveAIModel'](arg1);
}

export function StartAIChat(arg1) {
  return window['go']['main']['App']['StartAIChat'](arg1);
}

export function UpsertAIModel(arg1, arg2) {
  return window['go']['main']['App']['UpsertAIModel'](arg1, arg2);
}

export function UpsertAIModelV2(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpsertAIModelV2'](arg1, arg2, arg3);
}

export function UpsertAIModelV3(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpsertAIModelV3'](arg1, arg2, arg3, arg4, arg5);
}
